<?php

function qrblock_requirements($phase) {
  $requirements = array();
  
  if ($phase == 'install' && function_exists('libraries_get_path')) {
     $plupload_path = libraries_get_path('phpqrcode');
     if (!$plupload_path) {
       $requirements['plupload'] = array(
         'severity' => REQUIREMENT_ERROR,
         'description' => 'Secure File Share module requires !plupload, which is missing. Download and extract the entire contents of the archive into the %path directory on your server.',  array('!plupload' => l($t('Plupload Library'), 'https://github.com/aferrandini/PHPQRCode'), '%path' => '/libraries/phpqrcode'), 
       );
     }
  }
  return $requirements;
}